
export const SET_LOGIN_USER_DATA = "SET_LOGIN_USER_DATA";


export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILURET = "USER_REGISTRATION_FAILURET";

export const FETCH_BUDGET_lIST_REQUEST = "FETCH_BUDGET_lIST_REQUEST";
export const FETCH_BUDGET_lIST_SUCCESS = "FETCH_BUDGET_lIST_SUCCESS";
export const FETCH_BUDGET_lIST_FAILURE = "FETCH_BUDGET_lIST_FAILURE";

export const SAVE_BUDGET_REQUEST = "SAVE_BUDGET_REQUEST";
export const SAVE_BUDGET_SUCCESS = "SAVE_BUDGET_SUCCESS";
export const SAVE_BUDGET_FAILURE = "SAVE_BUDGET_FAILURE";

export const LOGOUT = "LOGOUT";


export const SET_MAIN_PAGE = "SET_MAIN_PAGE";
export const SET_SUB_PAGE = "SET_SUB_PAGE";


export const UI_INTRO_PAGE = "UI_INTRO_PAGE";
export const UI_LOGIN_PAGE = "UI_LOGIN_PAGE";
export const UI_REGISTRATION_PAGE = "UI_REGISTRATION_PAGE";
export const UI_BUDGET_PAGE = "UI_BUDGET_PAGE";

export const SUB_UI_ADD_FORM = "SUB_UI_ADD_FORM";
export const SUB_UI_EDIT_FORM = "SUB_UI_EDIT_FORM"


export const ALERT_TYPE_INFO = "ALERT_TYPE_INFO";
export const ALERT_TYPE_SUCCESS = "ALERT_TYPE_SUCCESS";
export const ALERT_TYPE_WARNNG = "ALERT_TYPE_WARNNG";
export const ALERT_TYPE_ERROR = "ALERT_TYPE_ERROR";